### ISSUE TITLE
Ortung des Helfers verbessern

### ISSUE THREAD

**Issue by MaxDuckwitz** [ZUKSev/ZUKS-Controller#23]
Die Ortung der Helfer funktioniert nicht einwandfrei. Ich wurde auf einem Friedhof in Mainz geortet, obwohl ich zu Hause in Nackenheim saß.

**Comment by Eldorado234** [comment]
Kann leider in der Browser nicht verbessert werden. Wird später auf mobilen Geräten kein Problem mehr sein.
