### ISSUE TITLE
Navigation -> Auswirkung auf den Client

### ISSUE THREAD

**Issue by MaxDuckwitz** [ZUKSev/ZUKS-Controller#25]
Die Eingabe eines Navigationspunktes für den Helfer hat keine Auswirkung auf den Helfer (Keine Karte mit dem Ort oder ähnliches auf dem Helferbildschirm)

Browser: Version 42.0.2311.135 m

**Comment by Eldorado234** [comment]
Ich habe die Stabilität der Verbindung zum Server für Nachrichten vom Controller erhöht. Bitte noch mal testen.
