### ISSUE TITLE
Messaging -> Helfer

### ISSUE THREAD

**Issue by MaxDuckwitz** [ZUKSev/ZUKS-Controller#26]
Das Verfassen einer Nachricht an einen Helfer hat keine Auswirkung auf den Helfer Bildschirm (Helfer erhält die Nachricht nicht).

Browser: Chrome Version 42.0.2311.135 m

**Comment by Eldorado234** [comment]
Sicher, dass du nicht statt `Senden` aus Versehen auf `Schließen` gedrückt hast? Ist mir auch gerade aus Versehen passiert - werde die UI von dem Aktions-Dialog noch mal überarbeiten.

**Comment by Eldorado234** [comment]
Ich habe die Stabilität der Verbindung zum Server für Nachrichten vom Controller erhöht. Bitte noch mal testen.
