### ISSUE TITLE
Gruppe anlegen -> Darstellung der Gruppe

### ISSUE THREAD

**Issue by MaxDuckwitz** [ZUKSev/ZUKS-Controller#27]
Nach dem Anlegen einer neuen Gruppe muss die Seite erst refreshed (F5) werden, damit die Gruppe angezeigt wird. 

Browser: Chrome Version 42.0.2311.135 m

**Comment by Eldorado234** [comment]
Ich habe die Stabilität der Verbindung zum Server für Nachrichten vom Controller erhöht. Bitte noch mal testen.
