### ISSUE TITLE
Ort anlegen

### ISSUE THREAD

**Issue by MaxDuckwitz** [ZUKSev/ZUKS-Controller#29]
Das Adressfeld in der Ort anlegen Karte nimmt keine Eingaben entgegen. Erst nach einem Klick auf den Standort-Butten rechts daneben wird eine Eingabe möglich.

**Comment by Eldorado234** [comment]
Ist Absicht, aber von der UI nicht sonderlich geschickt, das ist richtig.

**Comment by Eldorado234** [comment]
Ist angepasst. Vielleicht nicht mehr so schick wie vorher, aber hoffentlich besser zu verstehen.
