### ISSUE TITLE
Gruppe zuordnen

### ISSUE THREAD

**Issue by MaxDuckwitz** [ZUKSev/ZUKS-Controller#32]
Wenn ich einen Nutzer (Ei Gude) einer leeren Gruppe (Hellodd) zuordne, verschwindet der Nutzer aus der Helferliste und taucht nicht wieder auf, bis mit F5 ein refresh gemacht wird. Ist in der Gruppe bereits ein Nutzer, wird der danach hinzugefügte Nutzer (Max Duckwitz) direkt in der Gruppe gelistet und verschwindet NICHT.

**Comment by Eldorado234** [comment]
Ist behoben. Bitte noch mal testen.
