### ISSUE TITLE
Fix delivering of static files for admin website

### ISSUE THREAD

**Issue by Eldorado234** [ZUKSev/ZUKS-Controller#37]

**Comment by monofox** [comment]
,...? What does not work?

**Comment by Eldorado234** [comment]
Django redirects all static resources to `prototyp.zuks.org/static/...` which is not available yet. The webserver has to be configured to deliver the static files from a specific directory, which then has to be configured as `STATIC_ROOT` in the `server/server/settings.py`. `python manage.py collectstatic` is the last step to fix this issue in my opinion.

**Comment by Eldorado234** [comment]
Another problem is that django redirects to `http://prototyp.zuks.org/api-auth/login/?next=/` when the login button is clicked. This route is not available too. The correct url would be `http://prototyp.zuks.org/rest/api-auth/login/?next=/`, so there must be any option to tell django his root path.

**Comment by monofox** [comment]
You remember, why we introduced the local settings part for the website? Because i don't want to have the configuration file in the repository.

**Comment by Eldorado234** [comment]
Yes, it's still an open TODO for the Controller application. I create an issue for this topic, so we won't forget it.

**Comment by monofox** [comment]
OK. I fixed the other two points. In the other ticket i also mention what additionally needs to be changed so that it is working in a sub-directory.
