### ISSUE TITLE
include social media icons into feedback-dialog, instead of text only.

### ISSUE THREAD

**Issue by Quizzer** [ZUKSev/ZUKS-Controller#48]

**Comment by Quizzer** [comment]
added label enhancement

**Comment by Eldorado234** [comment]
They probably were removed when I merged the different development branches.

**Comment by Eldorado234** [comment]
I found the commit: https://github.com/ZUKSev/ZUKS-Controller/commit/ddf0ddcf77ac410aa2c6ef2b22748389ca265783 these changes just have to be reintegrated.
